### ISSUE TITLE
Another base ring conflict issue

### ISSUE THREAD

**Issue by MareoRaft** [MareoRaft/morse-code#13]
run

    sage: S = ShiftingOperatorAlgebra()
    sage: Sym = SymmetricFunctions(ZZ)
    sage: s = Sym.schur()
    sage: S[2, 1](s[4, 3, 2, 1]) 

and see what happens

**Comment by ghseeli** [comment]
Well, but this is solved by 
```
sage: S = ShiftingOperatorAlgebra(ZZ)
sage: Sym = SymmetricFunctions(ZZ)
sage: s = Sym.schur()
sage: S[2,1](s[4,3,2,1])
s[6, 4, 2, 1]
```

**Comment by MareoRaft** [comment]
Yes, the shifting operator and the schur function need to be constructed over the same ring.  

Otherwise the shifting operator can't act on the schur function.

Thanks George!

**Comment by MareoRaft** [comment]
It kindof sucks though that it doesn't work for subrings.
